services:
  db:
    image: postgres:17.5
    container_name: rps_postgres
    environment:
      POSTGRES_USER: rpsuser
      POSTGRES_PASSWORD: rpspass
      POSTGRES_DB: rpsdb
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U rpsuser']
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    build:
      context: .
      dockerfile: migrations.dockerfile
      args:
        FLYWAY_USER: rpsuser
        FLYWAY_PASSWORD: rpspass
        FLYWAY_HOST: db
        FLYWAY_PORT: 5432
        FLYWAY_DB: rpsdb
    depends_on:
      db:
        condition: service_healthy
