FROM flyway/flyway:11.8.1

ARG FLYWAY_USER
ARG FLYWAY_PASSWORD
ARG FLYWAY_HOST
ARG FLYWAY_PORT
ARG FLYWAY_DB

ENV FLYWAY_URL=jdbc:postgresql://${FLYWAY_HOST}:${FLYWAY_PORT}/${FLYWAY_DB}
ENV FLYWAY_USER=${FLYWAY_USER}
ENV FLYWAY_PASSWORD=${FLYWAY_PASSWORD}

COPY ./migrations /flyway/sql

CMD ["migrate"]
